"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastProvider } from "@/components/Toast/ToastContext";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow px-4 py-8">
            <div className="min-h-screen ">
              <div className="max-w-full mx-auto bg-gray-50 shadow-md rounded-lg p-4">
                <ToastProvider>{children}</ToastProvider>
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
